# SPDX-FileCopyrightText: 2026 VelesMist contributors
# SPDX-License-Identifier: MIT

name: OSV Scanner

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "41 3 * * 2"

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --recursive
            --format sarif
            --output osv-results.sarif
            .
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
        with:
          sarif_file: osv-results.sarif
