# SPDX-FileCopyrightText: 2026 VelesMist contributors
# SPDX-License-Identifier: MIT

name: REUSE

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: REUSE lint
        run: |
          python3 -m pip install --user reuse
          "$HOME/.local/bin/reuse" lint
